name: android-build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '17' }
      - name: Gradle build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: :apps:mobile:android:app:assembleDebug
